# generated by datamodel-codegen:
#   filename:  analysis.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, conint


class Resolution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    width: conint(ge=1)
    height: conint(ge=1)


class Source(StrEnum):
    """
    Which analyst produced this segment.
    """

    events = "events"
    visual = "visual"


class Energy(StrEnum):
    low = "low"
    medium = "medium"
    high = "high"


class Scene(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    start: confloat(ge=0.0)
    end: confloat(ge=0.0)
    source: Source = Field(..., description="Which analyst produced this segment.")
    summary: str | None = None
    energy: Energy | None = None
    ui_elements: list[str] | None = None
    keyframe_paths: list[str] | None = None


class Event(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., description="Stable event id used as caption anchor_event_id.")
    t: confloat(ge=0.0) = Field(
        ..., description="Timestamp (seconds) within the source video."
    )
    kind: str = Field(
        ..., description="Event type: click, keypress, navigation, modal_open, etc."
    )
    selector: str | None = None
    label: str | None = Field(
        None, description="Human-readable description, e.g. 'click Submit'."
    )
    payload: dict[str, Any] | None = None


class Analysis(BaseModel):
    """
    Scene analysis combining DOM-event-driven sections (event-log-analyst) and visual gap-fill sections (visual-analyst). Both write into the same artifact.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    duration_seconds: confloat(ge=0.0)
    fps: confloat(ge=1.0) | None = None
    resolution: Resolution | None = None
    scenes: list[Scene] = Field(
        ..., description="Ordered, non-overlapping scene segments."
    )
    events: list[Event] | None = Field(
        None,
        description="Discrete user-interaction or DOM events. Used by sfx-curator and as caption anchors.",
    )
