# generated by datamodel-codegen:
#   filename:  captions.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class Mood(StrEnum):
    announce = "announce"
    explain = "explain"
    punchline = "punchline"
    aside = "aside"
    callout = "callout"
    tagline = "tagline"


class Caption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    text: constr(min_length=1, max_length=80)
    mood: Mood
    anchor_event_id: str = Field(..., description="Refers to analysis.events[].id.")
    intent_duration: confloat(ge=0.5, le=8.0) = Field(
        ...,
        description="Author-intended on-screen duration in seconds. Composition may shift the start window for audio mixing but should respect this duration within tolerance.",
    )
    anchor_offset: float | None = Field(
        0,
        description="Seconds relative to the anchor event. Negative = before, positive = after.",
    )
    priority: conint(ge=1, le=5) | None = Field(
        3,
        description="1 = nice-to-have, 5 = must-show. Composition drops lower-priority captions if a window collides.",
    )


class Captions(BaseModel):
    """
    Anchor-based caption set per D4. Caption-writer owns (text, mood, anchor_event_id, intent_duration); composition-director derives absolute (start, end, duck_window) at compose time. No absolute timestamps live here.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    captions: list[Caption]
