# generated by datamodel-codegen:
#   filename:  composition.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, conint


class Resolution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    width: conint(ge=1)
    height: conint(ge=1)


class Footage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    src: str = Field(..., description="Path to footage.mp4 relative to the run dir.")
    trim_before: float | None = Field(
        0, description="Remotion v4 prop name (was trimLeft)."
    )
    trim_after: float | None = None


class Music(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    src: str
    gain_db: float | None = 0


class SfxItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    src: str
    t: confloat(ge=0.0) = Field(..., description="Absolute time in seconds.")
    gain_db: float | None = 0
    anchor_event_id: str | None = None


class Mix(BaseModel):
    """
    Targets enforced by qa-reviewer. YouTube-aligned per v2.1.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    integrated_lufs: float | None = -14
    true_peak_dbtp: float | None = -1
    duck_to_lufs: float | None = -22


class Audio(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    music: Music
    sfx: list[SfxItem]
    mix: Mix = Field(
        ..., description="Targets enforced by qa-reviewer. YouTube-aligned per v2.1."
    )


class Reason(StrEnum):
    priority_collision = "priority_collision"
    duration_overflow = "duration_overflow"
    anchor_density = "anchor_density"


class DroppedCaption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    reason: Reason
    details: str | None = None


class Preset(StrEnum):
    announce_clean = "announce-clean"
    explain_soft = "explain-soft"
    punchline_bold = "punchline-bold"
    retro_warm = "retro-warm"
    neutral = "neutral"


class Style(BaseModel):
    """
    Style preset selected by composition-director. Renderer looks up the implementation by name in remotion/src/styles/.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    preset: Preset


class Mood(StrEnum):
    announce = "announce"
    explain = "explain"
    punchline = "punchline"
    aside = "aside"
    callout = "callout"
    tagline = "tagline"


class DuckWindow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start: float | None = None
    end: float | None = None


class RenderedCaption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    text: str
    mood: Mood
    start: confloat(ge=0.0)
    end: confloat(ge=0.0)
    priority: conint(ge=1, le=5) = Field(
        ...,
        description="Carried through from captions.json; qa-reviewer uses this to reason about elision decisions.",
    )
    anchor_event_id: str | None = Field(
        None,
        description="Source anchor preserved for traceability after composition-director resolves absolute timing.",
    )
    duck_window: DuckWindow | None = None


class Composition(BaseModel):
    """
    Final composition specification consumed by Remotion's DemoVideo.tsx via renderMedia. composition-director resolves caption absolute timing (start/end/duck_window) from analysis events + caption anchors here. This is the artifact that crosses the Python/Node boundary, so codegen parity (Pydantic + Zod) is non-negotiable.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    fps: conint(ge=1)
    duration_seconds: confloat(ge=0.0)
    resolution: Resolution
    footage: Footage
    audio: Audio
    captions: list[RenderedCaption] = Field(
        ...,
        description="Caption layout WITH absolute timing resolved by composition-director (anchor_event_id + intent_duration → start/end/duck_window).",
    )
    dropped_captions: list[DroppedCaption] | None = Field(
        None,
        description="Captions that composition-director elided (collision resolution per priority). Preserved for qa-reviewer traceability.",
    )
    style: Style | None = Field(
        None,
        description="Style preset selected by composition-director. Renderer looks up the implementation by name in remotion/src/styles/.",
    )
