# generated by datamodel-codegen:
#   filename:  error.schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Error(BaseModel):
    """
    Standard error envelope emitted by CLI primitives (stderr) and agents (run-dir error.json) per D6.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    error: str = Field(..., description="Human-readable error message.")
    code: str = Field(
        ..., description="Stable machine-readable error code (e.g. CAPTURE_TCC_DENIED)."
    )
    retryable: bool = Field(
        ..., description="If true, the driver may retry once before escalating."
    )
    suggestion: str | None = Field(
        None, description="Remediation hint shown to the user."
    )
    stage: str | None = Field(
        None, description="Pipeline stage that produced the error."
    )
    context: dict[str, Any] | None = Field(
        None, description="Free-form structured context."
    )
