# generated by datamodel-codegen:
#   filename:  manifest.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint

from . import error_schema


class Kind(StrEnum):
    url = "url"
    video = "video"
    screen = "screen"


class Input(BaseModel):
    """
    What the user fed in.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    value: str


class Status(StrEnum):
    pending = "pending"
    running = "running"
    complete = "complete"
    failed = "failed"
    skipped = "skipped"


class Tokens(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input: int | None = None
    output: int | None = None


class Stage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(
        ...,
        description="Stable stage identifier (e.g. capture, analyze, music, compose).",
    )
    artifact: str = Field(
        ...,
        description="Path (relative to run dir) of the artifact this stage produces.",
    )
    owner: str = Field(..., description="Agent name responsible for this stage.")
    depends_on: list[str] = Field(
        ...,
        description="Names of upstream stages whose artifacts this stage consumes. Drives --from cascading invalidation.",
    )
    status: Status
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None
    duration_seconds: float | None = None
    artifact_sha256: str | None = Field(
        None,
        description="SHA256 of the produced artifact bytes. Driver uses this for content-aware --from invalidation: if a re-run produces an identical hash, downstream cascading is skipped.",
    )
    cost_usd: float | None = Field(
        None, description="Estimated cost of this stage (LLM tokens + API calls)."
    )
    tokens: Tokens | None = None
    attempts: conint(ge=0) | None = Field(
        None, description="Number of times the driver has dispatched this stage."
    )
    error: error_schema.Error | None = None


class RunManifest(BaseModel):
    """
    Per-run state file driving the deterministic dvg run pipeline. Encodes per-stage status, depends_on DAG (cascading invalidation), durations, and costs.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    run_id: str = Field(
        ..., description="Timestamp-based run identifier (e.g. 2026-05-03T22-42-00)."
    )
    input: Input = Field(..., description="What the user fed in.")
    config: dict[str, Any] | None = Field(
        None,
        description="Resolved run configuration (capture mode, target duration, etc.).",
    )
    stages: list[Stage] = Field(
        ...,
        description="Ordered pipeline stages. Driver walks this in order and dispatches the owning agent for any stage whose artifact is missing.",
    )
